@startuml

class App
class Server


package routes {
    class auctionRoutes
    class bidRoutes
    class cardPackRoutes
    class cardRoutes
    class deckRoutes
    class notificationRoutes
    class paypalRoutes
    class purchasesRoutes
    class transactionRoutes
    class userCardRoutes
    class userRoutes
}

package middleware {
    class authMiddleware
    class authSocket
}



package controllers {
    class auctionController
    class bidController
    class cardController
    class cardPackController
    class deckController
    class notificationController
    class paypalController
    class purchasesController
    class transactionController
    class userCardController
    class userController
}

package scripts {
    class fetchDecksData
    class fetchPokemonData
    class loadCardPacks
    class loadDecks
    class loadPokemonData
}

package models {
    entity auction 
    entity bid 
    entity card 
    entity cardPack 
    entity deck 
    entity notification 
    entity transaction 
    entity user 
    entity userCard 
    
    package utils {
        enum enums 
        class gymLeaders
        class validations
    }
}

@enduml