@startuml
participant "Administrador" as Admin
participant "Interfaz de Usuario" as UI
participant "Sistema de Gestión de Subastas" as AuctionSystem
participant "Sistema de Gestión de Notificaciones" as NotificationSystem
database "Base de Datos" as DB

== Inicio de Sesión ==
Admin -> UI : Inicia sesión

== Acceso a Subastas Activas ==
Admin -> UI : Selecciona "cerrar subastas finalizadas"
UI -> AuctionSystem : Solicita subastas finalizadas
AuctionSystem -> DB : Consulta subastas finalizadas
DB -> AuctionSystem : Retorna subastas finalizadas

== Procesamiento de Subastas ==
AuctionSystem -> DB : Identifica pujas ganadoras, actualiza las subastas y las pujas
DB -> AuctionSystem : Confirma actualización de subastas y pujas
AuctionSystem -> DB : Genera una transacción por cada puja y subasta procesada
DB -> AuctionSystem : Confirma el registro de transacciones

== Notificación ==
AuctionSystem -> DB : Transfiere montos y actualiza propietarios de cartas
DB -> AuctionSystem : Confirma las transferencias
AuctionSystem -> NotificationSystem: Registra las notificaciones a enviar.
NotificationSystem -> DB: Registra las notificaciones.
DB -> NotificationSystem: Confirma el registro de notificaciones.
NotificationSystem -> UI : Envía notificaciones en tiempo real.

== Respuesta al Administrador ==
AuctionSystem -> UI : Envía las subastas finalizadas actualizadas
UI -> Admin : Muestra los resultados de las subastas procesadas.

== Manejo de Errores ==
alt Error de conexión a la base de datos
    AuctionSystem -> UI : Muestra mensaje de error
    UI -> Admin : Muestra mensaje de error
end

== Finalización ==
Admin -> UI : Cierra sesión o continúa con otras tareas
@enduml



\subsubsubsection{Diagrama de secuencia. Cerrar subastas finalizadas} \label{sec:dsec_cerrar-subastas}
En la figura \ref{fig:seq-cerrar-subastas} se muestra el diagrama de secuencia correspondiente al caso de uso \textit{Cerrar subastas finalizadas}.
\begin{figure}[H]
    \centering
     \includegraphics[width=1\textwidth]{figures/6-Analisis/6-Casos-uso/6_3_4_DSec-cerrar-subastas.png}
    \caption{Diagrama de secuencia. Cerrar subastas finalizadas}
    \label{fig:seq-cerrar-subastas}
\end{figure}